service:
  name: onsen-store

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
  serverless-layers:
    layersDeploymentBucket: ${env:LAYER_DEPLOYMENT_BUCKET}
  ProgramsTable:
    name: !Ref ProgramsTable
    arn:  !GetAtt ProgramsTable.Arn

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-layers

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: 128
  profile: ${env:AWS_PROFILE_NAME}
  deploymentBucket:
    name: ${env:APP_DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - ${file(iam/ProgramsTableIAM.yml):ProgramsTableIAM}
functions:
  fetchPrograms:
    handler: src/handlers/programs/fetchPrograms.handler
    events:
      - http:
          method: get
          path: /programs

  fetchProgram:
    handler: src/handlers/programs/fetchProgram.handler
    events:
      - http:
          method: get
          path: /programs/{name}
          request:
            parameters:
              paths:
                name: true

resources:
  Resources:
    ProgramsTable: ${file(resources/ProgramsTable.yml):ProgramsTable}
