service:
  name: onsen-store

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
  serverless-layers:
    layersDeploymentBucket: ${env:LAYER_DEPLOYMENT_BUCKET}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-layers
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: 128
  profile: ${env:AWS_PROFILE_NAME}
  deploymentBucket:
    name: ${env:APP_DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  fetchPrograms:
    handler: src/handlers/fetchPrograms.handler
    events:
      - http:
          method: get
          path: /programs

  fetchProgram:
    handler: handler.fetchProgram
    events:
      - http:
          method: get
          path: /programs/{name}
          request:
            parameters:
              paths:
                name: true

resources:
  Resources:
    SubscriptionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        TableName: ${self:provider.environment.TABLE_SUBSCRIPTIONS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
