service:
  name: onsen-store
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
  serverless-layers:
    layersDeploymentBucket: ${env:LAYER_DEPLOYMENT_BUCKET}


# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-layers
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: 128
  profile: ${env:AWS_PROFILE_NAME}
  deploymentBucket:
    name: ${env:APP_DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  fetchPrograms:
    handler: handler.fetchPrograms
    events:
      - http:
          method: get
          path: programs

