ProgramsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ProgramsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: titleAlias
        AttributeType: S
    KeySchema:
      - AttributeName: titleAlias
        KeyType: HASH
